server:
  path: /
  proxy:
    x_for: 1
    x_proto: 1
    x_host: 1
  host: "0.0.0.0"
  port: 8080

# Local paths to modules and config
modules:
  plugins:
    provider:
      type: folder
      path: /data/pylon/plugins
  #
  requirements:
    mode: relaxed
    activation: bulk
    provider:
      type: folder
      path: /data/pylon/requirements
  #
  config:
    provider:
      type: folder
      path: /data/pylon/configs
  #
  preload:
    market:
      provider:
        type: git
        delete_git_dir: false
        depth: null
      source: https://github.com/carrier-io/market.git
      branch: main
#  skip:
#    - ui_performance

configs:
  market:
    local_preordered_plugins:
      - design-system
      - auth
      - projects
      - shared
      - tasks
      - secrets
      - backend_performance
      - artifacts
      - theme
      - integrations
      - reporter_email
      - reporter_jira
      - processing_severity_filter
      - scheduling
      - admin
      - ui_performance
      - aws_integration
      - azure_devops
      - kubernetes
      - gcp_integration
      - performance_analysis
      - s3_integration
      - email_base
      - email_template
      - shared_orch
      - security
      - security_sast
      - security_dependency
      - security_analysis
      - security_scanner_qualys
      - security_scanner_nikto
      - security_scanner_nmap
      - security_scanner_sslyze
      - security_scanner_w3af
      - security_scanner_masscan
      - security_scanner_aem
      - security_scanner_zap
      - security_scanner_trivy
      - security_scanner_retirejs
      - security_scanner_ruby
      - security_scanner_safety
      - security_scanner_python
      - security_scanner_npm
      - security_scanner_nodejsscan
      - security_scanner_nodejs
      - security_scanner_java
      - security_scanner_insider
      - security_scanner_gosec
      - security_scanner_golang
      - security_scanner_gitleaks
      - security_scanner_dependencycheck
      - security_scanner_csharp
      - security_scanner_brakeman
      - security_scanner_bandit
      - security_scanner_spotbugs
      - security_scanner_semgrep
      - azure_devops_integration
      # - system_reporter_email
      # - tasklets
      # - shared_orch
      # - engagements
      # - kanban
      # - issues
      # - kb
      # - reporter_engagement
  security:
    dast_image: "getcarrier/dast@sha256:3ed2c1302ad26ccd3a0efac879cd2b96caede16ff0cecca0b73729ea9718e1ab"
    control_tower_image: "getcarrier/control_tower@sha256:68c4c2effdc100a824b475208b1ef0d1037bc021718c7542594f9dc4f30dc849"
  security_sast:
    sast_image: "getcarrier/sast@sha256:ce648c18b87a47dd32356a7dd49b32595f413eaa128a98baa6635d0d7faa40d9"
    control_tower_image: "getcarrier/control_tower@sha256:68c4c2effdc100a824b475208b1ef0d1037bc021718c7542594f9dc4f30dc849"
  security_dependency:
    sca_image: "getcarrier/sast@sha256:ce648c18b87a47dd32356a7dd49b32595f413eaa128a98baa6635d0d7faa40d9"
    control_tower_image: "getcarrier/control_tower@sha256:68c4c2effdc100a824b475208b1ef0d1037bc021718c7542594f9dc4f30dc849"
  theme:
    change_password_url: "/auth/realms/carrier/account/password"
    # change_password_url: "https://account.activedirectory.windowsazure.com/ChangePassword.aspx"

# Session storage
sessions:
  redis:
    host: redis
    password: $REDIS_PASSWORD
  prefix: pylon_session_

# Traefik config
#traefik:
#  redis:
#    host: redis
#    password: $REDIS_PASSWORD
#  rootkey: traefik
#  entrypoint: https
#  rule: PathPrefix(`/`)
#  node_name: core
#  node_hostname: pylon

# Events queue
events:
  rabbitmq:
    host: rabbitmq
    port: 5672
    user: user
    password: $RABBIT_PASSWORD
    vhost: carrier
    queue: events
    hmac_key: key
    hmac_digest: sha512
    callback_workers: 16

# RPC
rpc:
  rabbitmq:
    host: rabbitmq
    port: 5672
    user: user
    password: $RABBIT_PASSWORD
    vhost: carrier
    queue: rpc
    hmac_key: key
    hmac_digest: sha512
    callback_workers: 16
  id_prefix: "core_"
  # trace: true

# Module/config storage
storage:
  endpoint: minio:9000
  access_key: admin
  secret_key: $MINIO_SECRET_KEY
  secure: false
  buckets:
    module: module
    config: config

# Loki logging settings
loki:
  buffering: true
  buffer_capacity: 1000
  buffer_flush_interval: 120
  buffer_flush_deadline: 300
  include_node_name: true
  include_level_name: true
  include_logger_name: true
  verify: true
  url: ${LOKI_HOST}


# Settings for Flask application
application:
  # EXPLAIN_TEMPLATE_LOADING: true
  # PREFERRED_URL_SCHEME: https
  # Sessions
  SECRET_KEY: $APP_SECRET_KEY
  SESSION_COOKIE_NAME: session_id

# dulwich git manager
git_manager:
  default:
    username:
    password:
    key:
    key_data:
