# General server config
server:
  #  path: /
  #  proxy: true
  host: "0.0.0.0"
  port: 8080

# Local paths to modules and config
modules:
  plugins:
    provider:
      type: folder
      path: /data/pylon/plugins
  #
  requirements:
    mode: relaxed
    provider:
      type: folder
      path: /data/pylon/requirements
  #
  config:
    provider:
      type: folder
      path: /data/pylon/configs
  #
  preload:
    market:
      provider:
        type: git
        delete_git_dir: false
        depth: null
        branch: main
      source: https://github.com/carrier-io/market.git
#  skip:
#    - ui_performance

configs:
  market:
    preordered_plugins:
      - design-system
      - auth
      - projects
      - shared
      - tasks
      - secrets
      - artifacts
      - theme
      - integrations
      - reporter_email
      - scheduling
      - admin
      - aws_integration
      - azure_devops
      - kubernetes
      - s3_integration
      - email_base
      - email_template
      - prompts
      - open_ai
      - vertex_ai
      - open_ai_azure

# Session storage
sessions:
  redis:
    host: redis
    password: password
  prefix: pylon_session_

# Traefik config
traefik:
  redis:
    host: redis
    password: password
  rootkey: traefik
  entrypoint: https
  rule: PathPrefix(`/`)
  node_name: core
  node_hostname: pylon

# Events queue
events:
  rabbitmq:
    host: rabbitmq
    port: 5672
    user: user
    password: password
    vhost: carrier
    queue: events
    hmac_key: key
    hmac_digest: sha512
    callback_workers: 16

# RPC
rpc:
  rabbitmq:
    host: rabbitmq
    port: 5672
    user: user
    password: password
    vhost: carrier
    queue: rpc
    hmac_key: key
    hmac_digest: sha512
    callback_workers: 16
  id_prefix: "core_"

# Module/config storage
storage:
  endpoint: minio:9000
  access_key: admin
  secret_key: password
  secure: false
  buckets:
    module: module
    config: config

# Loki logging settings
#loki:
#  buffering: true
#  buffer_capacity: 70
#  include_node_name: true
#  include_level_name: true
#  include_logger_name: true
#  verify: true
#  url: ${LOKI_HOST}


# Settings for Flask application
application:
  # SERVER_NAME: our.domain.here
  # EXPLAIN_TEMPLATE_LOADING: true
  # Sessions
#  PREFERRED_URL_SCHEME: https
  SECRET_KEY: SecretDevKeyForLocalUseOnlyChangedOnProd
  SESSION_COOKIE_NAME: session_id

# dulwich git manager
git_manager:
  default:
    username:
    password:
    key:
    key_data:
