server:
  #  path: /
  #  proxy: true
  host: "0.0.0.0"
  port: 8080

# Local paths to modules and config
modules:
  plugins:
    provider:
      type: folder
      path: /data/pylon/plugins
  #
  requirements:
    mode: relaxed
    provider:
      type: folder
      path: /data/pylon/requirements
  #
  config:
    provider:
      type: folder
      path: /data/pylon/configs
  #
  preload:
    market:
      provider:
        type: git
        delete_git_dir: false
        depth: null
      source: https://github.com/carrier-io/market.git
      branch: platform
#  skip:
#    - ui_performance

configs:
  market:
    local_preordered_plugins:
      - admin
      - artifacts
      - audit_logs
      - auth
      - auth_manager
      - auth_root
      - aws_integration
      - azure_devops_integration
      - backend_performance
      - design-system
      - email_base
      - email_template
      - engagements
      - gcp_integration
      - hugging_face
      - integrations
      - issues
      - kanban
      - kb
      - kubernetes
      - open_ai
      - performance_analysis
      - processing_severity_filter
      - projects
      - prompts
      - reporter_email
      - reporter_engagement
      - reporter_jira
      - s3_integration
      - scheduling
      - secrets
      - security
      - security_dependency
      - security_sast
      - security_scanner_aem
      - security_scanner_bandit
      - security_scanner_brakeman
      - security_scanner_csharp
      - security_scanner_dependencycheck
      - security_scanner_gitleaks
      - security_scanner_golang
      - security_scanner_gosec
      - security_scanner_insider
      - security_scanner_java
      - security_scanner_masscan
      - security_scanner_nikto
      - security_scanner_nmap
      - security_scanner_nodejs
      - security_scanner_nodejsscan
      - security_scanner_npm
      - security_scanner_python
      - security_scanner_qualys
      - security_scanner_retirejs
      - security_scanner_ruby
      - security_scanner_safety
      - security_scanner_semgrep
      - security_scanner_spotbugs
      - security_scanner_sslyze
      - security_scanner_trivy
      - security_scanner_w3af
      - security_scanner_zap
      - shared
      - shared_orch
      - tasks
      - theme
      - ui_performance
      - vertex_ai

# Session storage
sessions:
  redis:
    host: redis
    password: password
  prefix: pylon_session_

# Traefik config
#traefik:
#  redis:
#    host: redis
#    password: password
#  rootkey: traefik
#  entrypoint: https
#  rule: PathPrefix(`/`)
#  node_name: core
#  node_hostname: pylon

# Events queue
events:
  rabbitmq:
    host: rabbitmq
    port: 5672
    user: user
    password: password
    vhost: carrier
    queue: events
    hmac_key: key
    hmac_digest: sha512
    callback_workers: 16

# RPC
rpc:
  rabbitmq:
    host: rabbitmq
    port: 5672
    user: user
    password: password
    vhost: carrier
    queue: rpc
    hmac_key: key
    hmac_digest: sha512
    callback_workers: 16
  id_prefix: "core_"

# Module/config storage
storage:
  endpoint: minio:9000
  access_key: admin
  secret_key: password
  secure: false
  buckets:
    module: module
    config: config

# Loki logging settings
loki:
  buffering: true
  buffer_capacity: 70
  include_node_name: true
  include_level_name: true
  include_logger_name: true
  verify: true
  url: ${LOKI_HOST}


# Settings for Flask application
application:
  # EXPLAIN_TEMPLATE_LOADING: true
  # Sessions
#  PREFERRED_URL_SCHEME: https
  SECRET_KEY: SecretDevKeyForLocalUseOnlyChangedOnProd
  SESSION_COOKIE_NAME: session_id

# dulwich git manager
git_manager:
  default:
    username:
    password:
    key:
    key_data:
