apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.loki.name }}
  labels:
    {{- include "carrier-io.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.loki.type }}
  ports:
    - port: {{ .Values.services.loki.port }}
      {{- if .Values.services.loki.nodePort }}
      nodePort: {{ .Values.services.loki.nodePort }}
      {{- end }}
      targetPort: {{ .Values.services.loki.targetPort }}
      protocol: TCP
  selector:
    {{- include "carrier-io.specificSelectorLabels" (dict "name" "loki" "release" .Release.Name) | nindent 4 }}
