apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.services.pylon_auth.name }}-claim0
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
